"""change table name

Revision ID: 8e5ba693abcb
Revises: e9520ab3f6cc
Create Date: 2023-04-09 20:03:42.791083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e5ba693abcb'
down_revision = 'e9520ab3f6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('VIN', sa.String(length=100), nullable=False),
    sa.Column('car_brand', sa.String(length=20), nullable=False),
    sa.Column('car_model', sa.String(length=20), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('VIN')
    )
    op.drop_table('car_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('VIN', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('car_brand', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('car_model', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='car_model_pkey'),
    sa.UniqueConstraint('VIN', name='car_model_VIN_key')
    )
    op.drop_table('cars')
    # ### end Alembic commands ###
