"""create cars table

Revision ID: e9520ab3f6cc
Revises: 43c75c45d896
Create Date: 2023-04-09 20:01:27.625096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9520ab3f6cc'
down_revision = '43c75c45d896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('VIN', sa.String(length=100), nullable=False),
    sa.Column('car_brand', sa.String(length=20), nullable=False),
    sa.Column('car_model', sa.String(length=20), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('VIN')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_model')
    # ### end Alembic commands ###
